version: '3.9'

services:
  # Сервер
  ishop:
    build:
      context: .
      dockerfile: images/Server
    restart: always
    container_name: php_apache
    hostname: php_apache
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      MYSQL_DATABASE: ishop
    volumes:
      - ../:/var/www/html
    ports:
      - "80:80"

  # База данных
  db:
    image: mysql
    restart: always
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      MYSQL_DATABASE: ishop

  # Админка
  myadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      PMA_HOST: db
    ports:
      - "8080:80"